### PR TITLE
Fixed major spelling errors and Typos.

### PR DESCRIPTION
**Pull request by Sgouws**
:facepunch:

### CODE REVIEW

**Comment by Sgouws** [comment]
I wasn't sure what word you wanted to use on line 55, so I left it as is.

> Will `texh `exams allow formulas

**Comment by eonist** [comment]
Holy guacamole. Thanks man 😻 Sorry for the typos 🙁 I sort of write while I read. Im too inpatient to write synopsis after I finish the book. So there is a lot of typos in my book reviews usually. I Fixed a few earlier today but had to do some other things. 

Ill fix the other typos now. THX again. This book is really cool if you want to learn to learn. After this book you don't need more learning books IMO.

Let me know if you want input on something in the future.

See ya around buddy.  😃

**Comment by Sgouws** [comment]
Haha, that's all good, your super eloquent, I enjoy your writings, you should write a book someday :)
I can see that you're just running with what's in your head and just putting it down on 'paper', so don't stress about the typos :); I read the review this morning and thought I would fix it up, as it was a great review 🥇

Will do man, you do the same, I'll have a chat soon!

I'll definitely give it a read! 👍 

See ya!

**Comment by eonist** [comment]
Thx man. Book?  I wrote a really cool essay yesterday IMO. I'd love for you to read it. Right now it's a bit sensitive. And i don't  [Wanna Be Startin 🎶](https://www.youtube.com/watch?v=4Uj3zitETs4) ✌️

**Comment by Sgouws** [comment]
Yeah, you should write a book someday, like a novel. About anything, Unicorns, Stalin, a magical land :) Haha, thanks for the link. Yeah, would love to give it a read! 👍

**Comment by eonist** [comment]
@Sgouws Wrote an essay. Its really short. It takes 10 seconds to read  https://www.instagram.com/p/BWbAEo0BBoc/?taken-by=sepiadreamz

**Pull request merged**
